INSERT INTO Category_Message (description, type_category) VALUES
('SPORTS', 'SPORTS'),
('FINANCE', 'FINANCE'),
('MOVIES', 'MOVIES')
ON CONFLICT (type_category) DO NOTHING;


INSERT INTO Channel_Notification(type_Channel, description) VALUES ('SMS', 'SMS') ON CONFLICT (type_Channel) DO NOTHING;
INSERT INTO Channel_Notification(type_Channel, description) VALUES ('EMAIL', 'EMAIL') ON CONFLICT (type_Channel) DO NOTHING;
INSERT INTO Channel_Notification(type_Channel, description) VALUES ('PUSH_NOTIFICATION', 'PUSH_NOTIFICATION') ON CONFLICT (type_Channel) DO NOTHING;

INSERT INTO USER_CUSTOMER(EMAIL, NAME, PHONE_NUMBER) VALUES ('admin@mail.com', 'ADMIN', '45 8888899999') ON CONFLICT (email) DO NOTHING;
INSERT INTO USER_CUSTOMER(EMAIL, NAME, PHONE_NUMBER) VALUES ('taylor@mail.com', 'Taylor', '55 89898989') ON CONFLICT (email) DO NOTHING;
INSERT INTO USER_CUSTOMER(EMAIL, NAME, PHONE_NUMBER) VALUES ('bob@mail.com', 'BoB', '55 7777777') ON CONFLICT (email) DO NOTHING;
INSERT INTO USER_CUSTOMER(EMAIL, NAME, PHONE_NUMBER) VALUES ('steve@mail.com', 'Steve', '55 23232323') ON CONFLICT (email) DO NOTHING;
INSERT INTO USER_CUSTOMER(EMAIL, NAME, PHONE_NUMBER) VALUES ('joe@mail.com', 'Joe', '55 999990999') ON CONFLICT (email) DO NOTHING;
INSERT INTO USER_CUSTOMER(EMAIL, NAME, PHONE_NUMBER) VALUES ('rafael_souzagomes@mail.com', 'Rafael', '45 99999999') ON CONFLICT (email) DO NOTHING;

